image: $BUILD_IMAGE

stages:
    - build
    - deploy
    - publish

build:
    stage: build
    script:
        - autoreconf -fvi
        - ./configure --with-srcuri="$SRCURI" --enable-code-coverage
        - npm install
        - make all
        - make info pdf html
        - make check
    artifacts:
        paths:
            - doc/
            - coverage/
        expire_in: 30 min

eslint:
    stage: build
    image: $CI_REGISTRY/devops/docker-gts
    script:
        - cp /app/.eslintrc.json .
        - cp /app/.prettierrc.json .
        - eslint --ext .js,.ts .
    allow_failure: true
    before_script: []

pages:
    stage: deploy
    script:
        - mkdir -p public/doc
        - mv doc/liza.html/* doc/liza.pdf doc/liza.info public/
        - mkdir -p public/coverage
        - mv coverage/* public/coverage
    artifacts:
        paths:
            - public/
        expire_in: 30 min
    only:
        - tags

