image: $BUILD_IMAGE

stages:
    - build
    - deploy
    - publish

build:
    stage: build
    script:
        - autoreconf -fvi
        - ./configure --with-srcuri="$SRCURI" --enable-code-coverage
        - npm install
        - make all
        - make info pdf html
        - make check
    artifacts:
        paths:
            - doc/
            - coverage/
        expire_in: 30 min

pages:
    stage: deploy
    script:
        - mkdir -p public/doc
        - mv doc/liza.html/* doc/liza.pdf doc/liza.info public/
        - mkdir -p public/coverage
        - mv coverage/* public/coverage
    artifacts:
        paths:
            - public/
        expire_in: 30 min
    only:
        - tags

