image: $BUILD_IMAGE

include:
    - project: 'devops/shared-pipelines'
      file: '/jobs-common.yml'
    - project: 'devops/shared-pipelines'
      file: '/variables-public-deployment.yml'
    - project: 'devops/shared-pipelines'
      file: '/variables-internal-deployment.yml'

stages:
    - build
    - deploy
    - publish

build:
    stage: build
    script:
        - rm -rf node_modules/
        - autoreconf -fvi
        - ./configure --with-srcuri="$SRCURI" --enable-code-coverage
        - npm install
        - make all
        - make info pdf html
        - make check
    artifacts:
        paths:
            - "$CI_PROJECT_DIR"
        exclude:
            - "$CI_PROJECT_DIR/.git"
        expire_in: 30 min

pages:
    stage: deploy
    script:
        - mkdir -p public/doc
        - mv doc/liza.html/* doc/liza.pdf doc/liza.info public/
        - mkdir -p public/coverage
        - mv coverage/* public/coverage
    artifacts:
        paths:
            - public/
        expire_in: 30 min
    only:
        - tags

.dullahan:
    image: $CI_REGISTRY/devops/docker-rater-ci/image
    needs: ["build"]
    before_script:
        - eval $(ssh-agent -s)
        - ssh-add <(echo "$SSH_PRIVATE_KEY")

dullahan:deploy_prod:
    extends: [.dullahan]
    stage: deploy
    resource_group: "dullahan-deploy"
    script:
        - cp $ENV_FILE .env
        - for server in $PUBLIC_PROD_QUOTE1804_SERVERS; do
            ssh deploy@$server "mkdir -p /home/deploy/dullahan-prod";
            rsync -rzcPl --delete --exclude=.git/* . deploy@$server:dullahan-prod;
            ssh deploy@$server "sudo systemctl restart nodejs-dullahan-server-prod.service";
            done;
        - bin/sync-api-gateway-config "http://${KONG_PROD_SERVERS}:8000/kong-admin" conf/kong-prod.yml
    environment:
        name: production
    only:
        - tags

dullahan:deploy_demo:
    extends: [.dullahan]
    stage: deploy
    resource_group: "dullahan-deploy"
    script:
        - cp $ENV_FILE .env
        - for server in $PUBLIC_DEMO_QUOTE1804_SERVERS; do
            ssh deploy@$server "mkdir -p /home/deploy/dullahan-demo";
            rsync -rzcPl --delete --exclude=.git/* . deploy@$server:dullahan-demo;
            ssh deploy@$server "sudo systemctl restart nodejs-dullahan-server-demo.service";
            done;
        - bin/sync-api-gateway-config "http://${KONG_TEST_SERVERS}:8000/kong-admin" conf/kong-demo.yml
    environment:
        name: demo
    only:
        - tags

dullahan:deploy_test:
    extends: [.dullahan]
    stage: deploy
    resource_group: "dullahan-deploy"
    script:
        - cp $ENV_FILE .env
        - for server in $PUBLIC_TEST_QUOTE1804_SERVERS; do
            ssh deploy@$server "mkdir -p /home/deploy/dullahan-test";
            rsync -rzcPl --delete --exclude=.git/* . deploy@$server:dullahan-test;
            ssh deploy@$server "sudo systemctl restart nodejs-dullahan-server-test.service";
            done;
        - bin/sync-api-gateway-config "http://${KONG_TEST_SERVERS}:8000/kong-admin" conf/kong-test.yml
    environment:
        name: test
    only:
        - test

